### ISSUE TITLE
Actions that target multiple/all states

### ISSUE THREAD

**Issue by allforabit** [christianalfoni/react-states#1]
What do you think is the best way of dealing with this? I'm thinking of something like updating a text input in multiple states. Would you do it before the transition function? Or should there be a wildcard state to target all states? Or is it defeating the purpose of the state machine approach?

**Comment by allforabit** [comment]
Or maybe something like this:

```ts
const globalActions = {
  TEXT_UPDATE: ({ text }: Action & {type: "TEXT_UPDATE"}, state: State) => ({ ...state, text }),
  CURSOR_POS: ({ pos }: Action & {type: "CURSOR_POS"}, state: State) => ({ ...state, pos })
}

      transition(state, action, {
        editing: {
          ...globalActions,
         // other actions
        },
        editingHashtag: {
          ...globalActions,
         // other actions
        },
        editingLink: {
          ...globalActions,
         // other actions
        },
      }),
```

**Comment by christianalfoni** [comment]
Hi there @allforabit !

Yes! Exactly. When you have actions that covers multiple states, move them "up" and compose them in where needed. This avoids additional API surface and has the most flexibility. This is also why `state` is being passed as the second argument to the handler, so that you can isolate the handlers 😄 

I am considering adding helper types though. So:

```ts
export type PickState<
  S extends { state: string },
  SS extends State["state"]
> = State extends { state: SS } ? State : never;

export type PickAction<E extends { type: string }, T extends E["type"]> = E extends {
  type: T;
}
  ? E
  : never;
```

This would allow you to write:

```ts
const globalActions = {
  TEXT_UPDATE: ({ text }: PickAction<Action, "TEXT_UPDATE">, state: State) => ({ ...state, text }),
  CURSOR_POS: ({ pos }: PickAction<Action, "CURSOR_POS">, state: State) => ({ ...state, pos })
}
```

Not much change in characters, but just a bit more explicit 😄

**Comment by allforabit** [comment]
Lovely, I'll copy and paste those helpers in for now. Thanks @christianalfoni :-)
